### ISSUE TITLE
[ios] Creating Account in Simulator: TypeError: db.objects(...).filtered is not a function

### ISSUE THREAD

**Issue by Mnuzz** [Bit-Nation/BITNATION-Pangea-mobile#536]
## Feature / Issue
Reported at commit `b5261846c3385aa734a5b1fe1f9dcc210dc000e8`
Using ios simulator, when creating an account and clicking "Open Dashboard" (see screenshots), the app crashes with `TypeError: db.objects(...).filtered is not a function`

```
TypeError: db.objects(...).filtered is not a function
    at getAccount$ (/Users/personaluse/dev/bitnation/BITNATION-Pangea-mobile/src/sagas/accounts/sagas.js:114:41)
    at tryCatch (/Users/personaluse/dev/bitnation/BITNATION-Pangea-mobile/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/personaluse/dev/bitnation/BITNATION-Pangea-mobile/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/personaluse/dev/bitnation/BITNATION-Pangea-mobile/node_modules/regenerator-runtime/runtime.js:114:21)
    at next (/Users/personaluse/dev/bitnation/BITNATION-Pangea-mobile/node_modules/redux-saga/lib/internal/proc.js:322:27)
    at currCb (/Users/personaluse/dev/bitnation/BITNATION-Pangea-mobile/node_modules/redux-saga/lib/internal/proc.js:399:7)
    at tryCallOne (/Users/personaluse/dev/bitnation/BITNATION-Pangea-mobile/node_modules/promise/setimmediate/core.js:37:12)
    at /Users/personaluse/dev/bitnation/BITNATION-Pangea-mobile/node_modules/promise/setimmediate/core.js:123:15
    at /Users/personaluse/dev/bitnation/BITNATION-Pangea-mobile/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:301:18
    at _callTimer (/Users/personaluse/dev/bitnation/BITNATION-Pangea-mobile/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:154:7)
```
![image](https://user-images.githubusercontent.com/1613498/46585604-b1c7d980-ca27-11e8-87f3-60415d569fd8.png)

![image](https://user-images.githubusercontent.com/1613498/46585592-99f05580-ca27-11e8-9cd9-2cb90da31927.png)

## Acceptance criteria
Find root cause of this and ensure it is explained and solved

**Comment by Mnuzz** [comment]
Closing this issue, as the issue was opened by a member of the development team. Our new story board used internally will track the progress of this story from here out.
